services:
 
  react:
    container_name: react
    image: bondiolino/craf_test:frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    image: bondiolino/craf_test:backend
    ports:
      - 8000:8000
    environment:
      - DATABASE=postgres
      - SQL_DATABASE=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=core
      - SQL_PORT=5432
      - SQL_HOST=db
      - ALLOWED_HOST=crafttest.prueba
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12.0-alpine
    environment:
      - DATABASE=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=core
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: