name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '!backend/README.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '!backend/README.md'
  workflow_dispatch:


jobs:
  build:
      runs-on: ubuntu-latest
      #defaults:
      #   run:
      #    working-directory: ./backend
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Build and push Front
          uses: docker/build-push-action@v2
          with:
            file: backend/Dockerfile
            context: backend/
            tags: bondiolino/craf_test:backend
            push: true
