name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '!frontend/README.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '!frontend/README.md'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        - name: Build and push Front
          uses: docker/build-push-action@v2
          working-directory: ./frontend
          with:
            file: Dockerfile
            tags: bondiolino/craf_test:frontend
            push: true
