name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '!frontend/README.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '!frontend/README.md'
  workflow_dispatch:


jobs:
  build:
      runs-on: ubuntu-latest
      defaults:
         run:
          working-directory: ./frontend
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Debug
          run: |
            ls -lha
            pwd
            
            
        - name: Build and push Front
          uses: docker/build-push-action@v2
          with:
            file: Dockerfile
            tags: bondiolino/craf_test:frontend
            push: true
