name: Deploy to AWS EC2 with Terraform and Kubernetes

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main 
  #   paths-ignore:
  #     - 'backend/**'
  #     - '.github/workflows/build-*.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Apply Terraform to create EC2 instance
      working-directory: ./terraform
      id: apply_terraform
      run: terraform apply -auto-approve

    - name: Get EC2 instance IP
      id: get_instance_ip
      working-directory: ./terraform
      run: |
        # EC2_IP=$(terraform output -raw instance_ip)
        EC2_IP=$(terraform output -raw instance_ip | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
        echo "EC2_IP<<EOF" >> $GITHUB_ENV
        echo "$EC2_IP" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "EC2_IP is $EC2_IP"
      shell: bash